### ISSUE TITLE
gradio_client NOT FOUND

### ISSUE THREAD

**Issue by TobyGE** [freddyaboulton/gradio-tools#23]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[3], line 1
----> 1 from gradio_tools import (StableDiffusionTool, ImageCaptioningTool, StableDiffusionPromptGeneratorTool,
      2                           TextToVideoTool)
      4 from langchain.agents import initialize_agent
      5 from langchain.llms import OpenAI

File ~/Documents/LLM4Rec/gradio-tools/gradio_tools/__init__.py:1
----> 1 from gradio_tools.tools import (ClipInterrogatorTool,
      2                                 DocQueryDocumentAnsweringTool, GradioTool,
      3                                 ImageCaptioningTool, ImageToMusicTool,
      4                                 StableDiffusionPromptGeneratorTool,
      5                                 StableDiffusionTool, TextToVideoTool,
      6                                 WhisperAudioTranscriptionTool)
      8 __all__ = [
      9     "GradioTool",
     10     "StableDiffusionTool",
   (...)
     17     "DocQueryDocumentAnsweringTool",
     18 ]

File ~/Documents/LLM4Rec/gradio-tools/gradio_tools/tools/__init__.py:1
----> 1 from gradio_tools.tools.clip_interrogator import ClipInterrogatorTool
      2 from gradio_tools.tools.document_qa import DocQueryDocumentAnsweringTool
      3 from gradio_tools.tools.gradio_tool import GradioTool

File ~/Documents/LLM4Rec/gradio-tools/gradio_tools/tools/clip_interrogator.py:3
      1 from typing import TYPE_CHECKING
----> 3 from gradio_client.client import Job
      5 from gradio_tools.tools.gradio_tool import GradioTool
      7 if TYPE_CHECKING:

ModuleNotFoundError: No module named 'gradio_client'

**Comment by freddyaboulton** [comment]
Hi @TobyGE ! How did you install `gradio_tools`? `gradio_client` is listed as a dependency so I'm curious why it's not installed for you.

**Comment by TobyGE** [comment]
Thank you for your quick response. I just download the code. Let me try to install the gradio-tools package.
