### ISSUE TITLE
401 when trying to use token & duplicating the space 

### ISSUE THREAD

**Issue by koala73** [freddyaboulton/gradio-tools#27]
am just trying to pass a token- while duplicating the space 

`tools = [BarkTextToSpeechTool(hf_token="<token_hidden>",duplicate=True).langchain, StableDiffusionTool().langchain, StableDiffusionPromptGeneratorTool().langchain] 

`

the client is recognizing my space :
Using your existing Space: https://hf.space/eliehabib/bark 🤗

But am getting 401 , anything am missing or is it not supported ?

```
Traceback (most recent call last):
  File "/Users/eliehabib/miniconda3/lib/python3.10/site-packages/huggingface_hub/utils/_errors.py", line 259, in hf_raise_for_status
    response.raise_for_status()
  File "/Users/eliehabib/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/spaces/eliehabib/bark/hardware

```

**Comment by koala73** [comment]
Oh well, i can pass src="<my own space>" and it works without needing to duplicate.

**Comment by freddyaboulton** [comment]
Did you pass a write token to duplicate the space @koala73 ?

**Comment by koala73** [comment]
Yes I did , didn’t work 
Passing my duplicated space (done on hf  manually) and token worked

**Comment by freddyaboulton** [comment]
I'm glad you found a workaround @koala73 ! I think something changed in the internal HF API for duplicating spaces. Alerted the team and we'll try to get a fix out soon.

**Comment by koala73** [comment]
Good to know that I helped.
Thank you - and great job
