### ISSUE TITLE
Couldn't get readme example to work - workspaces wouldn't load

### ISSUE THREAD

**Issue by brettimus** [freddyaboulton/gradio-tools#31]
Could you add documentation on how to configure/use your own stable diffusion models? I got timeouts when trying to connect to the models that the stable diffusion tool relies on

Thanks for this project btw! Looks really cool and fits well with something I want to prototype

**Comment by giannisanni** [comment]
I ran in to an issue when using the stable diffusion tool today, it worked fine until then.
It seems it is trying to connect to https://huggingface.co/api/spaces/gradio-client-demos/stable-diffusion. This causes a gateway time-out error. My question is: shouldn’t it connect to https://huggingface.co/spaces/gradio-client-demos/stable-diffusion instead?

**Comment by freddyaboulton** [comment]
Hi @giannisanni ! I think the issue with the connection is that hugging face spaces went down briefly this morning. Should be back up now!

**Comment by freddyaboulton** [comment]
Hi @brettimus ! 

gradio-tools 0.0.9 is now released. This includes a new stable diffusion tool that can be easily duplicated when you pass in your own `hf_token`, i.e. `tool = StableDiffusionTool(hf_token="...", duplicate=True)`. That will create your own private version of the space. You can then upgrade the hardware. 
This should make it easier to avoid timeouts.

**Comment by brettimus** [comment]
Thanks! That's awesome. Appreciate the quick patch
