### ISSUE TITLE
Unable to run example

### ISSUE THREAD

**Issue by jeromeku** [freddyaboulton/gradio-tools#32]
Trying to run example from [documentation](https://www.gradio.app/gradio-and-llm-agents/) using StableDiffusionTool only.  On the latest version of Langchain (0.0.161) this results in a series of errors:
- First, `tools` has been refactored into a `langchain.tools`, where [BaseTools](https://github.com/hwchase17/langchain/blob/6f386628c2fc7e7dd45262c8c2a29b07c46f70ef/langchain/tools/base.py#L115) and [Tool](https://github.com/hwchase17/langchain/blob/6f386628c2fc7e7dd45262c8c2a29b07c46f70ef/langchain/tools/base.py#L302) are defined in `base.py`.
- The problem seems to be caused by `pydantic` validation, specifically:
```
ValidationError: 1 validation error for AgentExecutor
tools -> 0
  cannot pickle '_queue.SimpleQueue' object (type=type_error)
```
- The `AgentExecutor` class validates each of the tools passed in and because of the previous error, will give a cryptic error when calling the root validators [here](https://github.com/hwchase17/langchain/blob/f70e18a5b3a5c3205dfefd3c1470d42cd789f797/langchain/agents/agent.py#L626).  Because the above error (which you won't see unless you comment out / remove `root_validators`, you'll get a `KeyError` since tools fails because of the above per how pydantic [root validation](https://docs.pydantic.dev/latest/usage/validators/#root-validators) works

**Comment by freddyaboulton** [comment]
Hi @jeromeku !

What version of pydantic do you have? I can't reproduce the error with the following versions

```
❯ pip freeze | grep -E "pydantic|langchain"
langchain==0.0.161
openapi-schema-pydantic==1.2.4
pydantic==1.10.7
```

On the following script

```python
import os

if not os.getenv("OPENAI_API_KEY"):
    raise ValueError("OPENAI_API_KEY must be set")

from langchain.agents import initialize_agent
from langchain.llms import OpenAI
from gradio_tools.tools import (StableDiffusionTool, ImageCaptioningTool, StableDiffusionPromptGeneratorTool,
                                TextToVideoTool)

from langchain.memory import ConversationBufferMemory

llm = OpenAI(temperature=0)
memory = ConversationBufferMemory(memory_key="chat_history")
tools = [StableDiffusionTool().langchain,
         StableDiffusionPromptGeneratorTool().langchain, TextToVideoTool().langchain]


agent = initialize_agent(tools, llm, memory=memory, agent="conversational-react-description", verbose=True)
output = agent.run(input=("Please create a photo of a dog riding a skateboard "
                          "but improve my prompt prior to using an image generator."
                          "Please create a video for it using the improved prompt."))
```

Sample output so far

```
Loaded as API: https://gradio-client-demos-stable-diffusion.hf.space ✔
Loaded as API: https://microsoft-promptist.hf.space ✔
Loaded as API: https://damo-vilab-modelscope-text-to-video-synthesis.hf.space ✔


> Entering new AgentExecutor chain...

Thought: Do I need to use a tool? Yes
Action: StableDiffusionPromptGenerator
Action Input: A dog riding a skateboard
Job Status: Status.STARTING eta: None

Job Status: Status.PROCESSING eta: None

Observation: A dog riding a skateboard, digital painting, artstation, concept art, smooth, sharp focus, illustration, art by artgerm and greg rutkowski and alphonse mucha
Thought: Do I need to use a tool? Yes
Action: TextToVideo
Action Input: A dog riding a skateboard, digital painting, artstation, concept art, smooth, sharp focus, illustration, art by artgerm and greg rutkowski and alphonse mucha
Job Status: Status.STARTING eta: None
Due to heavy traffic on this app, the prediction will take approximately 62 seconds.For faster predictions without waiting in queue, you may duplicate the space using: Client.duplicate(damo-vilab/modelscope-text-to-video-synthesis)

Job Status: Status.IN_QUEUE eta: 62.15675727013619
```

**Comment by jeromeku** [comment]
Thanks for the response.

Not sure what was going on yesterday but re-ran example today and works fine -- I use a cloud dev env and likely was due to incompatible packages.

Thanks!
